# Generated by Django 5.2.5 on 2025-08-09 08:31

import apps.user.config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=apps.user.config.utils.profile_image_storage, validators=[apps.user.config.utils.validate_image_extension, apps.user.config.utils.validate_max_file_size]),
        ),
    ]
