# Generated by Django 5.2.5 on 2025-08-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_config', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
