# Generated by Django 5.2.5 on 2025-08-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_config', '0004_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('soft_delete_user', 'Can soft delete user'), ('hard_delete_user', 'Can hard delete user')]},
        ),
    ]
